### PR TITLE
Added iconfont and svg-sprites gulp tasks

### PR DESCRIPTION
**Pull request by koskinpark**
Added next features:
1. Automatic calculation of font-size in case of failback iconic font (when `no-cssmask` class).
2. Scale values and breakpoints. Now you can call g-icon() mixin and set breakpoints with scale values if you want, check usage https://github.com/skilld-labs/kaizen/pull/36/files#diff-2f9ab01abf385e71eb46e4f91b3d36b2R45

### CODE REVIEW

**Comment by hog-seruj** [comment]
I suggest adding SVG images to src/svg. It's a mixin and I should be able to use this mixin anywhere in theme. E/g: styles.scss

**Comment by andypost** [comment]
Btw I don't find icofont useful, I suppose we should use SVG everywhere and maintain bc-shim with fonts needs more work!
because if you create fonts you add font settings (woff2...ttf) dependency to pure sprite generarion

**Comment by koskinpark** [comment]
we can't use svg sprites in IE11, so no failback font means no icons there

**Comment by finnsky** [comment]
should be debug mode in mixin
[Image from Gyazo](https://gyazo.com/b8f0273a6270542e0d3bbdc7c2a4f465)

**Comment by koskinpark** [comment]
> should be debug mode in mixin
> [Image from Gyazo](https://gyazo.com/b8f0273a6270542e0d3bbdc7c2a4f465)

PR updated

**Comment by koskinpark** [comment]
PR was updated. Needs tests. All useful info about g-icon mixin you can find in comments there, but basically following usage is still enough to build your icon "as usual":
`.test-selector {
  @include g-icon((
    name: test
  ));
}`

It also can be on steroids for almost any case you may have in the reality of the project:
`.test3 {
  @include g-icon((
    name: test,
    scale: 2, // icon is 2x size by default
    bg: inherit,
    color: link,
    display: inline-block,
    vertical-align: middle,
    margin: 10px,
    breakpoints: (
      mobile_1x: 1, // show original size icon on this breakpoint
      mobile_2x: hidden // hide on this breakpoint
    )
  ));
}`

**Comment by hog-seruj** [comment]
I checked g-icon mixin:
1. Chrome - OK
2. IE 11 & Edge - OK
3. I added icons atom it works fine.

I think we can merge.

**Comment by koskinpark** [comment]
This pr is outdated, so let's close it.

**Pull request closed without merging**
