### PR TITLE
Gulp remove

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**

### CODE REVIEW

**Comment by koskinpark** [comment]
So core linter is strict, rules should be discussed. 
Also sass linter is not work.
createComponent task is not work.

Rest things are ok for me (watch, browsersync, debug, build and dev tasks)

**Comment by finnsky** [comment]
1. Added global browserlist config. Based on core.(pretty outdated) https://github.com/browserslist/browserslist
2. In local front tasks uses global core eslint settings from root drupal dir. (we need to manage it in docker somehow).
3. Removed gulp and dependencies.
4. Added prettier dependency based on core. All linters(js, sass, css) work with `--fix` flag
5. Added stylelint for css and sass. with current core settings for css.(pretty strict). and `stylelint-config-recommended-scss` for sass(still strict).
6. Splitted dependencies to devDependencies for local usage. and prod for docker/CI
7. Added lot of package.json tasks 
8. Removed sass importer. 
9. Updated post css config. 
10. Spitted all tasks to prod/dev
11. Added BundleAnalyzerPlugin for js to check bundle size in webpack with `--debug` flag.

**Comment by iberdinsky-skilld** [comment]
1. Added global browserlist config. Based on core.(pretty outdated) https://github.com/browserslist/browserslist
2. In local front tasks uses global core eslint settings from root drupal dir. (we need to manage it in docker somehow).
3. Removed gulp and dependencies.
4. Added prettier dependency based on core. All linters(js, sass, css) work with `--fix` flag
5. Added stylelint for css and sass. with current core settings for css.(pretty strict). and `stylelint-config-recommended-scss` for sass(still strict).
6. Splitted dependencies to devDependencies for local usage. and prod for docker/CI
7. Added lot of package.json tasks 
8. Removed sass importer. 
9. Updated post css config. 
10. Spitted all tasks to prod/dev
11. Added BundleAnalyzerPlugin for js to check bundle size in webpack with `--debug` flag.

**Comment by Megajack** [comment]
On `yarn build` command, getting an error: `Error: File to import not found or unreadable: bp.`

**Comment by iberdinsky-skilld** [comment]
1. Updated sass build, now both builds managed with webpack. 
2. Fixed breakpoints. Added common parser + nodesass importer + webpack loader. Now we will not create temp files like .bp.json and _breakpoints.sass to store variables. They will be added from yaml directly while compilation.

**Comment by iberdinsky-skilld** [comment]
gonna merge it, since it works on live project already.

**Pull request merged**
