### PR TITLE
layout creation from gulp task

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**
to test
`gulp cc` and confirm layout creation and check layout regions

### CODE REVIEW

**Comment by andypost** [comment]
Not sure it is needed because drush allows the same and I see no reason to duplicate

**Comment by iberdinsky-skilld** [comment]
> Not sure it is needed because drush allows the same and I see no reason to duplicate

Idea is to have tool which allow to create component with:

- sass src/implementation files
- twig template
- layout on demand with line in *.layouts.yml
- line in *.libraries.yml 
- line in *.components.yml
with one command. so it will be much comfortable to have it in one creation dialog imo

**Comment by hog-seruj** [comment]
Cool idea. But I'm not agreed that we must create a layout in atom, molecule, organism. I think it must be another directory ''layouts", file: _l-layoutName.scss.
Will be good to check region add, I think we can add regions as icon_map in layouts.yml.

**Comment by iberdinsky-skilld** [comment]
not actual anymore

**Pull request closed without merging**
