### PR TITLE
Adding static once.min.js

### PR DESCRIPTION
**Pull request by koskinpark**
Wtf https://www.npmjs.com/package/@drupal/once

### CODE REVIEW

**Comment by iberdinsky-skilld** [comment]
lgtm

**Comment by andypost** [comment]
Any reason to add it as static? It's available through npm

**Comment by andypost** [comment]
Also please provide description for pr and reason

The package is available via https://www.drupal.org/project/once

**Comment by andypost** [comment]
Or via https://www.npmjs.com/package/@drupal/once

**Comment by koskinpark** [comment]
Added https://www.npmjs.com/package/@drupal/once instead of static file

The reason is no internet sometimes. In our all components we have dependency on `once`, and if `once` will not be installed locally -> it will be impossible to continue building storybook's components without interner

**Comment by andypost** [comment]
Fixed commit message

**Pull request merged**
