### PR TITLE
added styles for header, breadcrumbs

### PR DESCRIPTION
**Pull request by koskinpark**
https://github.com/skilld-labs/kaizen/issues/105 Closes:
- breadcrumb
- header
- pager
- primary menu
- site branding
- site footer 
- tabs

### CODE REVIEW

**Comment by koskinpark** [comment]
Gonna add more components

**Comment by iberdinsky-skilld** [comment]
@koskinpark could you please attach some screenshots

**Comment by Megajack** [comment]
image
I think Status Message box needs some margins

**Comment by Megajack** [comment]
image
footer link has the same color as background

**Comment by Megajack** [comment]
image
let's move node links after body field

**Comment by iberdinsky-skilld** [comment]
lgtm

**Pull request merged**
