### PR TITLE
added storybook with twig/post-css support

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**
Added storybook support https://github.com/storybookjs/storybook

Works with twig(+some drupal filters) and custom data json. Supports post-css. 
All parts (twig, data, css) with livereload. 

## TODO

- [x] Add component based structure. one parent dir per Atoms/Molecules etc
- [x] Research useful storybook addons: https://storybook.js.org/addons/ Like https://github.com/storybookjs/storybook/tree/master/addons/knobs or 
https://github.com/storybookjs/storybook/tree/master/addons/links
- [x] Add component creation script with twig/json/*.stories.js files
- [x] Enjoy :)

## Testing

- create subtheme using `yarn cs` or cd to `STARTERKIT/basic/` -> `yarn`
-  `yarn run` storybook`

### CODE REVIEW

**Comment by iberdinsky-skilld** [comment]
[Image from Gyazo](https://gyazo.com/13930b673429ce3590c553d22c609e5a)

**Comment by koskinpark** [comment]
i'd say following step should be removed from `yarn cc` script:
```
{
    type: 'confirm',
    name: 'createAdditionalElements',
    message: 'Create elements instead default COMPONENT__content?',
    default: false,
  },
```

and also these ones should be combined:
```
{
    type: 'confirm',
    name: 'createStory',
    message: 'Create storybook component config?',
    default: true,
  },
  {
    type: 'confirm',
    name: 'createTemplate',
    message: 'Create twig template?',
    default: true,
  },
```

**Comment by koskinpark** [comment]
PR udpated

**Comment by iberdinsky-skilld** [comment]
fixed multiple values. added simple js script creation with ability to use inside storybook and external scripts.

**Pull request merged**
