### PR TITLE
Added feature to create subtheme from kaizen

### PR DESCRIPTION
**Pull request by koskinpark**
Usage:
`npm install` && `npm run cs`

TODO: add readme

### CODE REVIEW

**Comment by iberdinsky-skilld** [comment]
maybe we can do npx script for it?

https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by iberdinsky-skilld** [comment]
also i got error with screenshot.
[Image from Gyazo](https://gyazo.com/2eee9d6093ac38f124953fa8ba9d40ba)

**Comment by iberdinsky-skilld** [comment]
> maybe we can do npx script for it?
> 
> https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

this is how CRA does it

**Comment by iberdinsky-skilld** [comment]
also it rewrites package json credits 
```  "repository": "git@github.com:skilld-labs/subtheme.git",

**Comment by iberdinsky-skilld** [comment]
Let's merge it for now. only fix described problems please

**Comment by koskinpark** [comment]
MR updated with fixes of bugs

**Comment by iberdinsky-skilld** [comment]
yet another thing needed here. since it is planned to have themed starterkit we need to change location of starterkit to ./STARTERKIT/basic or something. gonna manage it

**Comment by iberdinsky-skilld** [comment]
also we need to add drupal colors somehow.

**Pull request merged**
