### PR TITLE
WIP Added styleguide config file.

### PR DESCRIPTION
**Pull request by iberdinsky-skilld**
Added simple config for usage with drupal styleguide module. 
To use it styleguide module should be patched with https://www.drupal.org/project/styleguide/issues/3025674

Here we need to research attaching any drupal entity in any view mode to styleguide. also needed to research parsing of custom twg file. we can port it to module later.

### CODE REVIEW

**Comment by iberdinsky-skilld** [comment]
one warning appears in drupal log
[Image from Gyazo](https://gyazo.com/64b0892dc955970635e572d9f89f20dc)

**Comment by hog-seruj** [comment]
I added patch but don't see custom components on stylesguide page.

**Comment by iberdinsky-skilld** [comment]
@hog-seruj was anything in dblog?

**Comment by iberdinsky-skilld** [comment]
PR should be updated with last changes from recent project

**Comment by hog-seruj** [comment]
If we use storybook, we can close this MR.

**Comment by iberdinsky-skilld** [comment]
not needed in current paradigm

**Pull request closed without merging**
